minimum_pre_commit_version: "3.5.0"
default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.13.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        stages: ["commit"]
      - id: detect-private-key
        stages: ["commit"]
      - id: check-case-conflict
        stages: ["commit"]
      # - id: no-commit-to-branch
      #   args: [--branch, "develop", --branch, "main"] # To prevent committing changes locally to develop
  - repo: https://github.com/errata-ai/vale
    rev: abcac76
    hooks:
      - id: vale
        args: [--output=line, --minAlertLevel=error]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        files: \.(md|mdx)$
        types: ["file"]
  # Useful for debugging hooks
  # - repo: meta
  #   hooks:
  #     - id: identity
